### ISSUE TITLE
Can't drag timeline handle from it's original starting position without pulling the whole page across.

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rio#155]

**Comment by bcsheesley** [comment]
It's probably my fat thumbs, but maybe it could use some more padding on the left edge?

**Comment by davidheyman** [comment]
I also can't get all the way to 2013

**Comment by kingfisher13** [comment]
I think 0639a32a87c497ce89555e1e35b9caddd0e94301 might have fixed this.

**Comment by davidheyman** [comment]
I thought this was fixed but it turned out I opened the page in a new tab so there was nothing to go _back_ to. Which brings up a hack of a fix:

1. Create a URL parameter that hides the intro screen when true
2. One mobile, have the **View the map** button open that link (with `?intro=false`) in a new tab

Any potential problems you can think of with this?

**Comment by kingfisher13** [comment]
FYI this isn't a problem with Android devices as they don't recognize swipes as navigation.

I increased the padding somewhat. Seems to work better for me, but I can only test on my iPad which is has a lot more screen real estate than the iphones.

Other than that, I don't see a problem with your solution @davidheyman. Let me know if that padding doesn't work and I'll integrate that.

**Comment by davidheyman** [comment]
It's better but I have to be really precise to get it. Let's do the
target=_blank skip intro solution which should be more reliable.
